# bncc_medio.py
# Versão FINAL e COMPLETA com TODAS as competências e habilidades do Ensino Médio,
# corrigida e validada a partir da contagem precisa dos arquivos fornecidos.

MEDIO_DB = {
    "Linguagens e suas Tecnologias": {
        "Competências Específicas": [
            {"codigo": 1, "descricao": "Compreender o funcionamento das diferentes linguagens e práticas culturais (artísticas, corporais e verbais) e mobilizar esses conhecimentos na recepção e produção de discursos nos diferentes campos de atuação social e nas diversas mídias, para ampliar as formas de participação social, o entendimento e as possibilidades de explicação e interpretação crítica da realidade e para continuar aprendendo."},
            {"codigo": 2, "descricao": "Compreender os processos identitários, conflitos e relações de poder que permeiam as práticas sociais de linguagem, respeitando as diversidades e a pluralidade de ideias e posições, e atuar socialmente com base em princípios e valores assentados na democracia, na igualdade e nos Direitos Humanos, exercitando o autoconhecimento, a empatia, o diálogo, a resolução de conflitos e a cooperação, e combatendo preconceitos de qualquer natureza."},
            {"codigo": 3, "descricao": "Utilizar diferentes linguagens (artísticas, corporais e verbais) para exercer, com autonomia e colaboração, protagonismo e autoria na vida pessoal e coletiva, de forma crítica, criativa, ética e solidária, defendendo pontos de vista que respeitem o outro e promovam os Direitos Humanos, a consciência socioambiental e o consumo responsável, em âmbito local, regional e global."},
            {"codigo": 4, "descricao": "Compreender as línguas como fenômeno (geo)político, histórico, cultural, social, variável, heterogêneo e sensível aos contextos de uso, reconhecendo suas variedades e vivenciando-as como formas de expressões identitárias, pessoais e coletivas, bem como agindo no enfrentamento de preconceitos de qualquer natureza."},
            {"codigo": 5, "descricao": "Compreender os processos de produção e negociação de sentidos nas práticas corporais, reconhecendo-as e vivenciando-as como formas de expressão de valores e identidades, em uma perspectiva democrática e de respeito à diversidade."},
            {"codigo": 6, "descricao": "Apreciar esteticamente as mais diversas produções artísticas e culturais, considerando suas características locais, regionais e globais, e mobilizar seus conhecimentos sobre as linguagens artísticas para dar significado e (re)construir produções autorais individuais e coletivas, exercendo protagonismo de maneira crítica e criativa, com respeito à diversidade de saberes, identidades e culturas."},
            {"codigo": 7, "descricao": "Mobilizar práticas de linguagem no universo digital, considerando as dimensões técnicas, críticas, criativas, éticas e estéticas, para expandir as formas de produzir sentidos, de engajar-se em práticas autorais e coletivas, e de aprender a aprender nos campos da ciência, cultura, trabalho, informação e vida pessoal e coletiva."}
        ],
        "Habilidades": [
            {"codigo": "EM13LGG101", "descricao": "Compreender e analisar processos de produção e circulação de discursos, nas diferentes linguagens, para fazer escolhas fundamentadas em função de interesses pessoais e coletivos."},
            {"codigo": "EM13LGG102", "descricao": "Analisar visões de mundo, conflitos de interesse, preconceitos e ideologias presentes nos discursos veiculados nas diferentes mídias, ampliando suas possibilidades de explicação, interpretação e intervenção crítica da/na realidade."},
            {"codigo": "EM13LGG103", "descricao": "Analisar o funcionamento das linguagens, para interpretar e produzir criticamente discursos em textos de diversas semioses (visuais, verbais, sonoras, gestuais)."},
            {"codigo": "EM13LGG104", "descricao": "Utilizar as diferentes linguagens, levando em conta seus funcionamentos, para a compreensão e produção de textos e discursos em diversos campos de atuação social."},
            {"codigo": "EM13LGG105", "descricao": "Analisar e experimentar diversos processos de remidiação de produções multissemióticas, multimídia e transmídia, desenvolvendo diferentes modos de participação e intervenção social."},
            {"codigo": "EM13LGG201", "descricao": "Utilizar as diversas linguagens (artísticas, corporais e verbais) em diferentes contextos, valorizando-as como fenômeno social, cultural, histórico, variável, heterogêneo e sensível aos contextos de uso."},
            {"codigo": "EM13LGG202", "descricao": "Analisar interesses, relações de poder e perspectivas de mundo nos discursos das diversas práticas de linguagem (artísticas, corporais e verbais), para compreender o modo como circulam, constituem-se e (re)produzem significação e ideologias."},
            {"codigo": "EM13LGG203", "descricao": "Analisar os diálogos e os processos de disputa por legitimidade nas práticas de linguagem e em suas produções (artísticas, corporais e verbais)."},
            {"codigo": "EM13LGG204", "descricao": "Dialogar e produzir entendimento mútuo, nas diversas linguagens (artísticas, corporais e verbais), em contextos de convivência, como forma de resolver conflitos e fortalecer a cooperação."},
            {"codigo": "EM13LGG301", "descricao": "Participar de processos de produção individual e colaborativa em diferentes linguagens (artísticas, corporais e verbais), levando em conta suas formas e seus funcionamentos, para produzir sentidos em diferentes contextos."},
            {"codigo": "EM13LGG302", "descricao": "Posicionar-se criticamente diante de diversas visões de mundo presentes nos discursos em diferentes linguagens, levando em conta seus contextos de produção e de circulação."},
            {"codigo": "EM13LGG303", "descricao": "Debater questões polêmicas de relevância social, analisando diferentes argumentos e opiniões, para formular, negociar e sustentar posições, frente à análise de perspectivas distintas."},
            {"codigo": "EM13LGG304", "descricao": "Formular propostas, intervir e participar de forma crítica e criativa de práticas de linguagem (artísticas, corporais e verbais) que demandem atuação coletiva e colaborativa."},
            {"codigo": "EM13LGG305", "descricao": "Mapear e criar, por meio de práticas de linguagem, possibilidades de atuação social, política, artística e cultural para enfrentar desafios contemporâneos."},
            {"codigo": "EM13LGG401", "descricao": "Analisar criticamente textos de modo a compreender e caracterizar as línguas como fenômeno (geo)político, histórico, social, cultural, variável, heterogêneo e sensível aos contextos de uso."},
            {"codigo": "EM13LGG402", "descricao": "Empregar, nas interações sociais, a variedade e o estilo de língua adequados à situação comunicativa, ao(s) interlocutor(es) e ao gênero do discurso."},
            {"codigo": "EM13LGG403", "descricao": "Fazer uso do inglês como língua de comunicação global, levando em conta a multiplicidade e variedade de usos, usuários e funções dessa língua no mundo contemporâneo."},
            {"codigo": "EM13LGG501", "descricao": "Selecionar e utilizar movimentos corporais de forma consciente e intencional para interagir socialmente em práticas corporais, de modo a estabelecer relações construtivas, empáticas, éticas e de respeito às diferenças."},
            {"codigo": "EM13LGG502", "descricao": "Analisar criticamente preconceitos, estereótipos e relações de poder presentes nas práticas corporais, adotando posicionamento contrário a qualquer manifestação de injustiça e desrespeito a direitos humanos e valores democráticos."},
            {"codigo": "EM13LGG503", "descricao": "Vivenciar práticas corporais e significá-las em seu projeto de vida, como forma de autoconhecimento, autocuidado físico e emocional, e de lazer."},
            {"codigo": "EM13LGG601", "descricao": "Apropriar-se do patrimônio artístico de diferentes tempos e lugares, compreendendo a sua diversidade, bem como os processos de legitimação das manifestações artísticas na sociedade."},
            {"codigo": "EM13LGG602", "descricao": "Fruir e apreciar esteticamente diversas manifestações artísticas e culturais, das locais às mundiais, assim como delas participar, de modo a aguçar continuamente a sensibilidade, a imaginação e a criatividade."},
            {"codigo": "EM13LGG603", "descricao": "Expressar-se e atuar em processos de criação autorais individuais e coletivos nas diferentes linguagens artísticas (artes visuais, audiovisual, dança, música e teatro) e nas intersecções entre elas."},
            {"codigo": "EM13LGG604", "descricao": "Relacionar as práticas artísticas às diferentes dimensões da vida social, cultural, política e econômica e identificar o processo de construção histórica dessas práticas."},
            {"codigo": "EM13LGG701", "descricao": "Explorar tecnologias digitais da informação e comunicação (TDIC), compreendendo seus princípios e funcionalidades, e utilizá-las de modo ético, criativo, responsável e adequado a práticas de linguagem em diferentes contextos."},
            {"codigo": "EM13LGG702", "descricao": "Avaliar o impacto das tecnologias digitais da informação e comunicação (TDIC) na formação do sujeito e em suas práticas sociais, para fazer uso crítico dessa mídia em práticas de seleção, compreensão e produção de discursos em ambiente digital."},
            {"codigo": "EM13LGG703", "descricao": "Utilizar diferentes linguagens, mídias e ferramentas digitais em processos de produção coletiva, colaborativa e projetos autorais em ambientes digitais."},
            {"codigo": "EM13LGG704", "descricao": "Apropriar-se criticamente de processos de pesquisa e busca de informação, por meio de ferramentas e dos novos formatos de produção e distribuição do conhecimento na cultura de rede."},
            {"codigo": "EM13LP01", "descricao": "Relacionar o texto com suas condições de produção e seu contexto sócio-histórico de circulação (leitor/audiência previstos, objetivos, pontos de vista e perspectivas, papel social do autor, época, gênero do discurso etc.), de forma a ampliar as possibilidades de construção de sentidos e de análise crítica e produzir textos adequados a diferentes situações."},
            {"codigo": "EM13LP02", "descricao": "Estabelecer relações entre as partes do texto, tanto na produção como na leitura/escuta, considerando a construção composicional e o estilo do gênero."}
        ]
    },
    "Matemática e suas Tecnologias": {
        "Competências Específicas": [
            {"codigo": 1, "descricao": "Utilizar estratégias, conceitos e procedimentos matemáticos para interpretar situações em diversos contextos, sejam atividades cotidianas, sejam fatos das Ciências da Natureza e Humanas, das questões socioeconômicas ou tecnológicas, divulgados por diferentes meios, de modo a contribuir para uma formação geral."},
            {"codigo": 2, "descricao": "Propor ou participar de ações para investigar desafios do mundo contemporâneo e tomar decisões éticas e socialmente responsáveis, com base na análise de problemas sociais, como os voltados a situações de saúde, sustentabilidade, das implicações da tecnologia no mundo do trabalho, entre outros, mobilizando e articulando conceitos, procedimentos e linguagens próprios da Matemática."},
            {"codigo": 3, "descricao": "Utilizar estratégias, conceitos, definições e procedimentos matemáticos para interpretar, construir modelos e resolver problemas em diversos contextos, analisando a plausibilidade dos resultados e a adequação das soluções propostas, de modo a construir argumentação consistente."},
            {"codigo": 4, "descricao": "Compreender e utilizar, com flexibilidade e precisão, diferentes registros de representação matemáticos (algébrico, geométrico, estatístico, computacional etc.), na busca de solução e comunicação de resultados de problemas."},
            {"codigo": 5, "descricao": "Investigar e estabelecer conjecturas a respeito de diferentes conceitos e propriedades matemáticas, empregando estratégias e recursos, como observação de padrões, experimentações e diferentes tecnologias, identificando a necessidade, ou não, de uma demonstração cada vez mais formal na validação das referidas conjecturas."}
        ],
        "Habilidades": [
            {"codigo": "EM13MAT101", "descricao": "Interpretar criticamente situações econômicas, sociais e fatos relativos às Ciências da Natureza que envolvam a variação de grandezas."},
            {"codigo": "EM13MAT102", "descricao": "Analisar tabelas, gráficos e amostras de pesquisas estatísticas apresentadas em relatórios divulgados por diferentes meios de comunicação, identificando, quando for o caso, inadequações que possam induzir a erros de interpretação."},
            {"codigo": "EM13MAT103", "descricao": "Interpretar e compreender textos científicos ou divulgados pelas mídias, que empregam unidades de medida de diferentes grandezas e as conversões possíveis entre elas."},
            {"codigo": "EM13MAT104", "descricao": "Interpretar taxas e índices de natureza socioeconômica (índice de desenvolvimento humano, taxas de inflação, entre outros)."},
            {"codigo": "EM13MAT105", "descricao": "Utilizar as noções de transformações isométricas (translação, reflexão, rotação) e transformações homotéticas para construir figuras e analisar elementos da natureza e diferentes produções humanas."},
            {"codigo": "EM13MAT106", "descricao": "Analisar a extração de informações de diferentes representações de um mesmo conjunto de dados (tabelas, gráficos de barras, de colunas, de setores e de linhas)."},
            {"codigo": "EM13MAT201", "descricao": "Propor ou participar de ações adequadas às demandas da região, preferencialmente de sua comunidade, envolvendo medições e cálculos de perímetro, de área, de volume, de capacidade ou de massa."},
            {"codigo": "EM13MAT202", "descricao": "Analisar e comparar situações que envolvam juros simples e compostos, com o uso de planilhas eletrônicas ou aplicativos."},
            {"codigo": "EM13MAT203", "descricao": "Aplicar conceitos matemáticos no planejamento, na execução e na análise de ações envolvendo a utilização de aplicativos e a criação de planilhas."},
            {"codigo": "EM13MAT301", "descricao": "Resolver e elaborar problemas do cotidiano, da Matemática e de outras áreas do conhecimento, que envolvem equações lineares e sistemas lineares."},
            {"codigo": "EM13MAT302", "descricao": "Construir modelos em linguagem matemática, para resolver problemas em diferentes contextos, avaliando sua adequação."},
            {"codigo": "EM13MAT303", "descricao": "Interpretar e comparar cenários sobre juros simples e compostos, utilizando aplicativos de simulação."},
            {"codigo": "EM13MAT304", "descricao": "Resolver e elaborar problemas com funções logarítmicas nos quais seja necessário compreender e interpretar a variação das grandezas envolvidas."},
            {"codigo": "EM13MAT305", "descricao": "Resolver e elaborar problemas com funções exponenciais nos quais seja necessário compreender e interpretar a variação das grandezas envolvidas."},
            {"codigo": "EM13MAT306", "descricao": "Resolver e elaborar problemas em contextos que envolvem fenômenos periódicos reais e suas representações por funções seno e cosseno."},
            {"codigo": "EM13MAT307", "descricao": "Empregar diferentes métodos para a obtenção da medida da área de uma superfície (reconfigurações, aproximação por cortes etc.)."},
            {"codigo": "EM13MAT308", "descricao": "Resolver e elaborar problemas de contagem envolvendo agrupamentos ordenáveis ou não de elementos, por meio dos princípios multiplicativo e aditivo."},
            {"codigo": "EM13MAT309", "descricao": "Resolver e elaborar problemas que envolvem o cálculo de áreas totais e de volumes de prismas, pirâmides e corpos redondos em situações reais."},
            {"codigo": "EM13MAT310", "descricao": "Resolver e elaborar problemas que envolvem cálculo de probabilidade de eventos em experimentos aleatórios equiprováveis."},
            {"codigo": "EM13MAT311", "descricao": "Identificar e descrever o espaço amostral de eventos aleatórios, realizando contagem das possibilidades."},
            {"codigo": "EM13MAT312", "descricao": "Resolver e elaborar problemas que envolvem o cálculo da probabilidade da união e da intersecção de eventos em experimentos aleatórios."},
            {"codigo": "EM13MAT313", "descricao": "Aplicar conceitos de um poliedro em situações-problema, para calcular, por exemplo, o número de vértices, faces e arestas."},
            {"codigo": "EM13MAT314", "descricao": "Resolver e elaborar problemas que envolvem cálculo de volumes de figuras compostas por sólidos usuais."},
            {"codigo": "EM13MAT315", "descricao": "Investigar e registrar, por meio de um fluxograma, os passos para a resolução de um grupo de problemas."},
            {"codigo": "EM13MAT316", "descricao": "Construir e interpretar tabelas e gráficos de frequências com base em dados obtidos em pesquisas por amostras estatísticas."},
            {"codigo": "EM13MAT401", "descricao": "Converter representações algébricas de funções polinomiais de 1º e 2º graus para representações geométricas no plano cartesiano."},
            {"codigo": "EM13MAT402", "descricao": "Analisar relações de interdependência entre grandezas em um problema, representadas por funções, para avaliar o comportamento de uma delas em função da outra."},
            {"codigo": "EM13MAT403", "descricao": "Analisar e estabelecer relações, com ou sem apoio de tecnologias digitais, entre as representações de uma função (tabelas, gráficos e leis de formação)."},
            {"codigo": "EM13MAT404", "descricao": "Analisar funções definidas por uma ou mais sentenças (nas representações algébrica e gráfica) e suas propriedades."},
            {"codigo": "EM13MAT405", "descricao": "Utilizar conceitos de porcentagem e de juros simples e compostos na análise de problemas de educação financeira."},
            {"codigo": "EM13MAT406", "descricao": "Construir e interpretar gráficos de funções polinomiais de 1º e 2º graus, de funções exponenciais e logarítmicas."},
            {"codigo": "EM13MAT407", "descricao": "Identificar e associar sequências numéricas (PA e PG) a funções afins e exponenciais, respectivamente."},
            {"codigo": "EM13MAT501", "descricao": "Investigar relações entre números expressos em tabelas para representá-los no plano cartesiano, identificando padrões e criando conjecturas para generalizar e expressar algebricamente essa generalização."},
            {"codigo": "EM13MAT502", "descricao": "Investigar e discutir o uso de diferentes linguagens (gráficos, tabelas, textos, etc.) na representação de dados estatísticos."},
            {"codigo": "EM13MAT503", "descricao": "Investigar pontos de máximo ou de mínimo de funções quadráticas em contextos envolvendo superfícies, trajetórias de projéteis etc."},
            {"codigo": "EM13MAT504", "descricao": "Investigar processo de obtenção da média, da amplitude e do desvio padrão de um conjunto de dados estatísticos."},
            {"codigo": "EM13MAT505", "descricao": "Resolver problemas sobre ladrilhamento do plano, com ou sem apoio de aplicativos de geometria dinâmica."},
            {"codigo": "EM13MAT506", "descricao": "Representar graficamente a variação da área e do perímetro de um polígono regular quando os comprimentos de seus lados variam."},
            {"codigo": "EM13MAT507", "descricao": "Identificar e associar progressões aritméticas (PA) a funções afins de domínios discretos."},
            {"codigo": "EM13MAT508", "descricao": "Identificar e associar progressões geométricas (PG) a funções exponenciais de domínios discretos."},
            {"codigo": "EM13MAT509", "descricao": "Investigar a deformação de ângulos e áreas provocada pelas diferentes projeções usadas em cartografia."},
            {"codigo": "EM13MAT510", "descricao": "Investigar conjuntos de dados relativos ao comportamento de duas variáveis numéricas, usando ou não tecnologias da informação."},
            {"codigo": "EM13MAT511", "descricao": "Reconhecer a existência de diferentes tipos de espaços amostrais, discretos ou não, e de eventos, equiprováveis ou não, e investigar as implicações no cálculo de probabilidades."}
        ]
    },
    "Ciências da Natureza e suas Tecnologias": {
        "Competências Específicas": [
            {"codigo": 1, "descricao": "Analisar fenômenos naturais e processos tecnológicos, com base nas interações e relações entre matéria e energia, para propor ações individuais e coletivas que aperfeiçoem processos produtivos, minimizem impactos socioambientais e melhorem as condições de vida em âmbito local, regional e global."},
            {"codigo": 2, "descricao": "Analisar e utilizar interpretações sobre a dinâmica da Vida, da Terra e do Cosmos para elaborar argumentos, realizar previsões sobre o funcionamento e a evolução dos seres vivos e do Universo, e fundamentar e defender decisões éticas e responsáveis."},
            {"codigo": 3, "descricao": "Investigar situações-problema e avaliar aplicações do conhecimento científico e tecnológico e suas implicações no mundo, utilizando procedimentos e linguagens próprios das Ciências da Natureza, para propor soluções que considerem demandas locais, regionais e/ou globais."}
        ],
        "Habilidades": [
            {"codigo": "EM13CNT101", "descricao": "Analisar e representar, com ou sem o uso de dispositivos e de aplicativos digitais, as transformações e conservações em sistemas que envolvam quantidade de matéria, de energia e de movimento."},
            {"codigo": "EM13CNT102", "descricao": "Realizar previsões, avaliar intervenções e/ou construir protótipos de sistemas térmicos que visem à sustentabilidade."},
            {"codigo": "EM13CNT103", "descricao": "Utilizar o conhecimento sobre as radiações e suas origens para avaliar as potencialidades e os riscos de sua aplicação em equipamentos de uso cotidiano, na saúde, no ambiente, na indústria e na agricultura."},
            {"codigo": "EM13CNT104", "descricao": "Avaliar os benefícios e os riscos à saúde e ao ambiente, considerando a composição, a toxicidade e a reatividade de diferentes materiais e produtos."},
            {"codigo": "EM13CNT105", "descricao": "Analisar os ciclos biogeoquímicos e interpretar os efeitos de fenômenos e ações humanas sobre esses ciclos."},
            {"codigo": "EM13CNT106", "descricao": "Avaliar, com ou sem o uso de dispositivos e aplicativos digitais, tecnologias e possíveis soluções para as demandas que envolvem a geração, o transporte, a distribuição e o consumo de energia elétrica."},
            {"codigo": "EM13CNT107", "descricao": "Realizar previsões sobre os níveis de degradação do ambiente, para propor e implementar medidas de prevenção e remediação."},
            {"codigo": "EM13CNT108", "descricao": "Identificar e explicar as propriedades da matéria que permitem o funcionamento de equipamentos e a escolha de materiais adequados para construção de objetos."},
            {"codigo": "EM13CNT201", "descricao": "Analisar e discutir modelos, teorias e leis propostos em diferentes épocas e culturas para comparar distintas explicações sobre o surgimento e a evolução da Vida, da Terra e do Universo."},
            {"codigo": "EM13CNT202", "descricao": "Analisar as diversas formas de manifestação da vida em seus diferentes níveis de organização, bem como as condições ambientais favoráveis e os fatores limitantes a elas."},
            {"codigo": "EM13CNT203", "descricao": "Aplicar os conhecimentos da evolução biológica para analisar a história humana, considerando sua origem, diversificação, dispersão pelo planeta e diferentes formas de interação com a natureza."},
            {"codigo": "EM13CNT204", "descricao": "Elaborar explicações, previsões e cálculos a respeito dos movimentos de objetos na Terra, no Sistema Solar e no Universo com base na análise das interações gravitacionais."},
            {"codigo": "EM13CNT205", "descricao": "Interpretar resultados e realizar previsões sobre atividades experimentais, fenômenos naturais e processos tecnológicos, com base nas noções de probabilidade e incerteza."},
            {"codigo": "EM13CNT206", "descricao": "Discutir a importância da preservação e conservação da biodiversidade, considerando parâmetros qualitativos e quantitativos."},
            {"codigo": "EM13CNT207", "descricao": "Identificar, analisar e discutir vulnerabilidades vinculadas às vivências e aos desafios contemporâneos aos quais as juventudes estão expostas."},
            {"codigo": "EM13CNT208", "descricao": "Aplicar os princípios da hereditariedade e da biologia molecular para analisar e prever características fenotípicas de seres vivos."},
            {"codigo": "EM13CNT209", "descricao": "Analisar a evolução dos seres vivos e as modificações nos ambientes, e as suas inter-relações."},
            {"codigo": "EM13CNT301", "descricao": "Construir questões, elaborar hipóteses, previsões e estimativas, empregar instrumentos de medição e representar e interpretar modelos explicativos para investigar e analisar fenôomens naturais."},
            {"codigo": "EM13CNT302", "descricao": "Comunicar, para públicos variados, em diversos contextos, resultados de análises, pesquisas e/ou experimentos."},
            {"codigo": "EM13CNT303", "descricao": "Interpretar textos de divulgação científica que tratem de temáticas das Ciências da Natureza, disponíveis em diferentes mídias."},
            {"codigo": "EM13CNT304", "descricao": "Analisar e debater o papel do conhecimento científico e tecnológico no combate a preconceitos, em diferentes contextos histórico-sociais."},
            {"codigo": "EM13CNT305", "descricao": "Investigar e analisar os usos de recursos naturais da biosfera, com destaque para o Brasil, e discutir a importância da conservação, para o desenvolvimento social e econômico."},
            {"codigo": "EM13CNT306", "descricao": "Avaliar os riscos envolvidos em atividades cotidianas, aplicando conhecimentos das Ciências da Natureza, para justificar o uso de equipamentos e recursos."},
            {"codigo": "EM13CNT307", "descricao": "Analisar as propriedades dos materiais para avaliar a adequação de seu uso em diferentes aplicações."},
            {"codigo": "EM13CNT308", "descricao": "Investigar e analisar o funcionamento de equipamentos elétricos e/ou eletrônicos e sistemas de automação para compreender as tecnologias contemporâneas."},
            {"codigo": "EM13CNT309", "descricao": "Analisar questões socioambientais, políticas e econômicas relativas à dependência do mundo atual em relação aos recursos não renováveis."},
            {"codigo": "EM13CNT310", "descricao": "Investigar e analisar os efeitos de programas de infraestrutura e demais serviços básicos (saneamento, energia elétrica, transporte, etc.)."}
        ]
    },
    "Ciências Humanas e Sociais Aplicadas": {
        "Competências Específicas": [
            {"codigo": 1, "descricao": "Analisar processos políticos, econômicos, sociais, ambientais e culturais nos âmbitos local, regional, nacional e mundial em diferentes tempos, a partir da pluralidade de procedimentos epistemológicos, científicos e tecnológicos."},
            {"codigo": 2, "descricao": "Analisar a formação de territórios e fronteiras em diferentes tempos e espaços, mediante a compreensão das relações de poder que determinam as territorialidades e o papel geopolítico dos Estados-nações."},
            {"codigo": 3, "descricao": "Analisar e avaliar criticamente as relações de diferentes grupos, povos e sociedades com a natureza (produção, distribuição e consumo) e seus impactos econômicos e socioambientais."},
            {"codigo": 4, "descricao": "Analisar as relações de produção, capital e trabalho em diferentes territórios, contextos e culturas, discutindo o papel dessas relações na construção, consolidação e transformação das sociedades."},
            {"codigo": 5, "descricao": "Identificar e combater as diversas formas de injustiça, preconceito e violência, adotando princípios éticos, democráticos, inclusivos e solidários, e respeitando os Direitos Humanos."},
            {"codigo": 6, "descricao": "Participar do debate público de forma crítica, respeitando diferentes posições e fazendo escolhas alinhadas ao exercício da cidadania e ao seu projeto de vida, com liberdade, autonomia, consciência crítica e responsabilidade."}
        ],
        "Habilidades": [
            {"codigo": "EM13CHS101", "descricao": "Identificar, analisar e comparar diferentes fontes e narrativas expressas em diversas linguagens, com vistas à compreensão de ideias filosóficas e de processos e eventos históricos, geográficos, políticos, econômicos, sociais, ambientais e culturais."},
            {"codigo": "EM13CHS102", "descricao": "Identificar, analisar e discutir as circunstâncias históricas, geográficas, políticas, econômicas, sociais, ambientais e culturais de matrizes conceituais."},
            {"codigo": "EM13CHS103", "descricao": "Elaborar hipóteses, selecionar evidências e compor argumentos relativos a processos políticos, econômicos, sociais, ambientais, culturais e epistemológicos."},
            {"codigo": "EM13CHS104", "descricao": "Analisar objetos e vestígios da cultura material e imaterial de modo a identificar conhecimentos, valores, crenças e práticas que caracterizam a identidade e a diversidade cultural de diferentes sociedades."},
            {"codigo": "EM13CHS105", "descricao": "Identificar, contextualizar e criticar tipologias de organização política e social, tais como cidade-estado, império, Estado-Nação etc."},
            {"codigo": "EM13CHS106", "descricao": "Utilizar as linguagens cartográfica, gráfica e iconográfica, diferentes gêneros textuais e tecnologias digitais de informação e comunicação de forma crítica, significativa, reflexiva e ética nas diversas práticas sociais."},
            {"codigo": "EM13CHS201", "descricao": "Analisar e caracterizar as dinâmicas das populações, das mercadorias e do capital nos diversos continentes, com destaque para a mobilidade e a fixação de pessoas."},
            {"codigo": "EM13CHS202", "descricao": "Analisar e avaliar os impactos das tecnologias na estruturação e nas dinâmicas de grupos, povos e sociedades contemporâneos (fluxos populacionais, financeiros, de mercadorias, de informações, de valores éticos e culturais etc.)."},
            {"codigo": "EM13CHS203", "descricao": "Comparar os significados de território, fronteiras e vazio (espacial, temporal e cultural) em diferentes sociedades e contextos."},
            {"codigo": "EM13CHS204", "descricao": "Comparar e avaliar os processos de ocupação do espaço e a formação de territórios, territorialidades e fronteiras."},
            {"codigo": "EM13CHS205", "descricao": "Analisar a produção de diferentes territorialidades em suas dimensões culturais, econômicas, ambientais, políticas e sociais, no Brasil e no mundo contemporâneo."},
            {"codigo": "EM13CHS206", "descricao": "Analisar a ocupação humana e a produção do espaço em diferentes tempos, aplicando os princípios de localização, distribuição, ordem, extensão, conexão, arranjos, causalidade, entre outros."},
            {"codigo": "EM13CHS301", "descricao": "Elaborar hipóteses, selecionar evidências e compor argumentos relativos a processos políticos, econômicos, sociais, ambientais, culturais e epistemológicos, com base na sistematização de dados e informações de diversas naturezas."},
            {"codigo": "EM13CHS302", "descricao": "Analisar e avaliar criticamente os impactos econômicos e socioambientais de cadeias produtivas ligadas à exploração de recursos naturais e às atividades agropecuárias em diferentes ambientes e escalas de análise."},
            {"codigo": "EM13CHS303", "descricao": "Debater e avaliar o papel da indústria cultural e das culturas de massa no estímulo ao consumismo e seus impactos socioambientais."},
            {"codigo": "EM13CHS304", "descricao": "Analisar os impactos socioambientais decorrentes de práticas de instituições governamentais, de empresas e de indivíduos."},
            {"codigo": "EM13CHS305", "descricao": "Analisar e discutir o papel e as competências de organismos internacionais e ONGs na proposição de soluções para problemas ambientais."},
            {"codigo": "EM13CHS306", "descricao": "Contextualizar, comparar e avaliar os impactos de diferentes modelos socioeconômicos no uso dos recursos naturais e na promoção da sustentabilidade."},
            {"codigo": "EM13CHS401", "descricao": "Identificar e analisar as relações entre sujeitos, grupos, classes sociais e sociedades com culturas e modelos de produção, de modo a problematizar as desigualdades e as violências."},
            {"codigo": "EM13CHS402", "descricao": "Analisar e comparar indicadores de emprego, trabalho e renda em diferentes espaços, escalas e tempos, associando-os a processos de estratificação e desigualdade socioeconômica."},
            {"codigo": "EM13CHS403", "descricao": "Caracterizar e analisar os impactos das transformações tecnológicas nas relações sociais e de trabalho no mundo contemporâneo."},
            {"codigo": "EM13CHS404", "descricao": "Discutir o papel dos valores e das moedas nos sistemas econômicos e financeiros em diferentes tempos e espaços."},
            {"codigo": "EM13CHS501", "descricao": "Analisar os fundamentos da ética em diferentes culturas, tempos e espaços, identificando processos que contribuem para a formação de sujeitos éticos que valorizem a liberdade, a cooperação, a autonomia, o empreendedorismo e a convivência democrática."},
            {"codigo": "EM13CHS502", "descricao": "Analisar situações da vida cotidiana, estilos de vida, valores, condutas etc., desnaturalizando e problematizando formas de desigualdade, preconceito, intolerância e discriminação."},
            {"codigo": "EM13CHS503", "descricao": "Identificar diversas formas de violência (física, simbólica, psicológica etc.), suas principais vítimas, suas causas sociais, psicológicas e afetivas."},
            {"codigo": "EM13CHS504", "descricao": "Analisar e avaliar os impasses ético-políticos decorrentes das transformações científicas e tecnológicas no mundo contemporâneo."},
            {"codigo": "EM13CHS601", "descricao": "Identificar e analisar as demandas e os protagonismos políticos, sociais e culturais dos povos indígenas e das populações afrodescendentes no Brasil contemporâneo."},
            {"codigo": "EM13CHS602", "descricao": "Identificar e caracterizar a presença do paternalismo, do autoritarismo e do populismo na política, na sociedade e nas culturas brasileira e latino-americana."},
            {"codigo": "EM13CHS603", "descricao": "Analisar a formação de diferentes países, povos e nações e de suas experiências políticas e de exercício da cidadania, aplicando conceitos políticos básicos."},
            {"codigo": "EM13CHS604", "descricao": "Discutir o papel dos organismos internacionais no contexto mundial, com vistas à elaboração de uma visão crítica sobre seus limites e suas formas de atuação nos países."},
            {"codigo": "EM13CHS605", "descricao": "Analisar os princípios da declaração dos Direitos Humanos, recorrendo às noções de justiça, igualdade e fraternidade."},
            {"codigo": "EM13CHS606", "descricao": "Analisar as características socioeconômicas da sociedade brasileira e propor medidas para enfrentar os problemas identificados e construir uma sociedade mais próspera, justa e inclusiva."}
        ]
    }
}
